Fix "Cannot read property 'request' of undefined"
frctl/twig pull request #22
Opened 2019-02-20 17:28 UTC by julmot

A "render" template like e.g.:

```twig
{% render "@utility-nav" %}
{% render "@header" %}
```

triggers the following error:

![000016](https://user-images.githubusercontent.com/8310677/53111318-25810380-353d-11e9-860a-e65d27e1fbd8.png)

The reason being that `let request = env.request || this.context._request;` is executed before the check of `env`.

2019-02-21 14:37 UTC, Chapabu requested changes

2019-02-21 14:37 UTC, Chapabu commented on src/filters/path.js
> +        } else {
Just a stylistic thing, but we can drop the `else` here. We're already returning if the problem properties don't exist.

2019-02-21 15:09 UTC, risker commented
Not sure about this. It will probably resolve the error, but that `request` variable should always be defined, otherwise the path filter will not output the expected result.

I've encountered this while using the `only` keyword on my includes, or when using multiple nested `embed` and `include` tags. This might also be related to an upstream twig.js bug: https://github.com/twigjs/twig.js/issues/287

2019-12-05 19:55 UTC, risker commented
This has been resolved in the meantime by #28

2019-12-05 19:55 UTC, closed without merging